name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: get-date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-

      - name: Cache Buildozer working directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev \
              python3-dev python3-pip libsqlite3-dev zlib1g-dev \
              libncurses5 libncurses5-dev libreadline-dev libgdbm-dev \
              libbz2-dev liblzma-dev openjdk-11-jdk unzip git
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Delete cached .buildozer folders (clean build)
        run: |
          rm -rf .buildozer
          rm -rf .buildozer_global

      - name: Build APK with Buildozer (verbose)
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
