name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.10
        run: |
          sudo apt update
          sudo apt install -y python3.10 python3.10-dev python3.10-distutils
          sudo apt install -y python3-pip
          python3.10 -m pip install --upgrade pip

      - name: Install Buildozer and dependencies
        run: |
          sudo apt install -y build-essential libssl-dev libffi-dev \
              python3.10-dev libsqlite3-dev zlib1g-dev \
              libncurses5 libncurses5-dev libreadline-dev libgdbm-dev \
              libbz2-dev liblzma-dev openjdk-11-jdk unzip git
          pip install cython
          pip install buildozer

      - name: Set up Android SDK
        run: |
          # Install Android SDK tools
          sudo apt-get install -y wget unzip

          # Install Android SDK
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          rm commandlinetools-linux-7583922_latest.zip

          # Update SDK manager
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --update

          # Accept licenses
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses

          # Install required SDK components (platform tools, build tools, platforms)
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;36.0.0" "platforms;android-30"

      - name: Cache Buildozer working directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
