name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.10
        run: |
          sudo apt update
          sudo apt install -y python3.10 python3.10-dev python3.10-distutils python3-pip
          python3.10 -m pip install --upgrade pip
          sudo ln -sf /usr/bin/python3.10 /usr/bin/python

      - name: Install dependencies and Buildozer
        run: |
          sudo apt install -y build-essential libssl-dev libffi-dev \
              libsqlite3-dev zlib1g-dev libncurses5-dev libreadline-dev \
              libgdbm-dev libbz2-dev liblzma-dev openjdk-11-jdk unzip git curl
          python -m pip install --upgrade cython buildozer

      - name: Download and install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"

      - name: Symlink expected tools/bin path for sdkmanager
        run: |
          mkdir -p $HOME/android-sdk/tools/bin
          ln -sf $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/android-sdk/tools/bin/sdkmanager

      - name: Build APK
        env:
          ANDROIDSDK: ${{ env.HOME }}/android-sdk
          ANDROIDNDK: ${{ env.HOME }}/android-sdk/ndk/25.1.8937393
        run: |
          echo "sdk.dir=$ANDROIDSDK" >> ~/.buildozer/android/platform/android-sdk/.android/repositories.cfg || true
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
