name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.10
        run: |
          sudo apt update
          sudo apt install -y python3.10 python3.10-dev python3.10-distutils
          sudo apt install -y python3-pip
          python3.10 -m pip install --upgrade pip

      - name: Install Buildozer and dependencies
        run: |
          sudo apt install -y build-essential libssl-dev libffi-dev \
              python3.10-dev libsqlite3-dev zlib1g-dev \
              libncurses5 libncurses5-dev libreadline-dev libgdbm-dev \
              libbz2-dev liblzma-dev openjdk-11-jdk unzip git
          pip install cython
          pip install buildozer

      - name: Cache Buildozer working directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
