name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.10
        run: |
          sudo apt update
          sudo apt install -y python3.10 python3.10-dev python3.10-distutils python3-pip
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install virtualenv
        shell: bash

      - name: Set up Python 3.10 venv
        run: |
          python3.10 -m virtualenv venv
          source venv/bin/activate
          pip install cython buildozer

      - name: Install build dependencies
        run: |
          sudo apt install -y build-essential libssl-dev libffi-dev \
            libsqlite3-dev zlib1g-dev libncurses5 libncurses5-dev \
            libreadline-dev libgdbm-dev libbz2-dev liblzma-dev openjdk-11-jdk unzip wget git

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d tmp
          mkdir latest
          mv tmp/cmdline-tools/* latest/
          rm -rf tmp cmdline-tools.zip
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Cache Buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build APK with Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
